theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

markdown: kramdown

title: Philip Chung, MD, MS
description: Anesthesiologist & Healthcare AI Researcher
headshot: /assets/img/PhilipHeadshot2022.jpg

me:
  website_url: https://philipchung.github.io/
  linkedin_url: https://www.linkedin.com/in/philipchung/
  googlescholar_url: https://scholar.google.com/citations?hl=en&user=30ay-W8AAAAJ
  cv_pdf_url: https://docs.google.com/viewer?url=https://github.com/philipchung/philipchung.github.io/raw/main/assets/pdfs/PhilipChungCV.pdf"
links:
  apt_regional: https://philipchung.github.io/apt-regional/intro/intro.html